### ISSUE TITLE
Error after initial install.

### ISSUE THREAD

**Issue by skelley213** [KangaCoders/newrelic_openvpn_agent#1]
After installing I keep getting the following error "Error occurred in poll cycle: divided by 0". It then tells me o statistics gathered and shuts down. Any suggestions?

**Comment by kaiiserni** [comment]
Hi skelley213,

What is the path to your openvpn status log? And can you also share the content please?
Also, I have to ask, are you absolutely sure the openvpn service is running?

Grts

**Comment by skelley213** [comment]
Thanks for the quick reply. My server config was not set to write out to my status log. Fixed it just 2 minutes before you emailed me and it looks like it is working great! Thanks for the great plugin! 5Stars

**Comment by kaiiserni** [comment]
I’m happy to hear you fixed it. Enjoy! :-)
